<?php

require('fpdf.php');
include_once'connect.php';
include_once'db.php';
ob_end_clean();

class PDF extends FPDF
{
// Page header
function Header()
{
    // Logo
$this->SetY(5);
$this->SetFont('Arial','',14);
$this->Cell(0,20,'SANGAM FASHIONS (Buyers Details)',0,1,'C');

}

// Page footer
function Footer()
{ 

    // Position at 1.5 cm from bottom
    $this->SetY(-10);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,10,'Page '.'generated by i-BILL',0,0,'L');
    $this->Cell(-31,10,'powered by',0,0,'R');
    $this->Image('icoders.jpg',170,287,9*2.6,3*2);
}

}
// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial','',14);

$pdf->SetFont('Arial','',10);
$r=$dbclass->select_normal('*','buyer_base',"ORDER BY buyers_name ASC",$dbc);
if(!isset($p))
    $p=1;
while($t=mysqli_fetch_assoc($r)){
    
   $pdf->Cell(60,16,$pdf->SetFont('Arial','B',12).$pdf->Write(5,$t['buyers_name']).$pdf->Ln().$pdf->SetFont('Arial','',9).$pdf->MultiCell(40,5,$t['buyers_address'],0,'C').$pdf->write(5,$t['buyers_no']." Email: ".$t['buyers_email']),0,1,'J');
$p++;
}


$pdf->Output('contact.pdf','I');


?>